# cloud building testing, only builds
# react-app currently

steps:
  # install react-app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-app', '.']

  # docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app']

  # Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'run',
        'deploy',
        '$_SERVICE-NAME',
        '--image',
        'gcr.io/$PROJECT_ID/react-app',
        '--region',
        '$_DEPLOY_REGION',
      ]
    entrypoint: gcloud
images:
  - 'gcr.io/$PROJECT_ID/react-app'
